### ISSUE TITLE
Infrastructure for precomputed bindings

### ISSUE THREAD

**Issue by clauswilke** [extendr/libR-sys#26]
Given the various issues we have with compilation on Windows, I think we need tools for precomputed bindings as soon as possible. So I've started implementing this. See here: https://github.com/clauswilke/libR-sys/tree/precomputed_bindings

Generate bindings by setting the `LIBRSYS_BINDINGS_OUTPUT_PATH` variable to provide an output location:
```
LIBRSYS_BINDINGS_OUTPUT_PATH=~/Desktop cargo build
```

Then move the bindings into the `bindings` folder of the crate: https://github.com/clauswilke/libR-sys/tree/precomputed_bindings/bindings

Then build and test with these bindings by setting the `--no-default-features` flag (you may have to run `cargo clean` to trigger the rebuild):
```
cargo build --no-default-features
cargo test --no-default-features
```

I'd be particularly interested in knowing whether it's possible to generate bindings under 64-bit windows and use under 32-bit windows. If somebody could test that that would be great. I assume you'll have to change the architecture name from `x86_64` to `x86` in the bindings file name for this to work.

cc @Ilia-Kosenkov @CGMossa @yutannihilation

**Comment by clauswilke** [comment]
I changed the name of the env var to specify the output path. It is now `LIBRSYS_BINDINGS_OUTPUT_PATH` (I edited the comment above). And I also added `LIBRSYS_BINDINGS_PATH` to specify an alternative location for the precomputed bindings. So you should now be able to do something like the following:

```
LIBRSYS_BINDINGS_OUTPUT_PATH=~/Desktop cargo build
cargo clean
LIBRSYS_BINDINGS_PATH=~/Desktop cargo build --no-default-features
```

**Comment by yutannihilation** [comment]
I got `Cannot find R major version` error on MSYS2 MinGW64. It seems

https://github.com/clauswilke/libR-sys/blob/fa6601c7a54abd81707925fcfd55662ccf8b10af/build.rs#L175-L185

returns nothing. This is because the R process errors with this:

```
Fatal error: option \'-e\' requires a non-empty argument\r\n\r\n
```

Besides, if I remove linebreaks, I still see this error. Seems `"` is not properly escaped

```
Error in strsplit(R.version$minor, ., fixed = TRUE) : \r\n  object \'.\' not found\r\nExecution halted\r\n
```

<details>
<summary>full error</summary>

``` console
$ RUST_BACKTRACE=1 LIBRSYS_BINDINGS_OUTPUT_PATH=/c/Users/hiroaki-yutani/Desktop/ /c/Users/hiroaki-yutani/.cargo/bin/cargo build
   Compiling libR-sys v0.1.10 (C:\Users\hiroaki-yutani\Documents\repo\R\libR-sys)
error: failed to run custom build command for `libR-sys v0.1.10 (C:\Users\hiroaki-yutani\Documents\repo\R\libR-sys)`

Caused by:
  process didn't exit successfully: `C:\Users\hiroaki-yutani\Documents\repo\R\libR-sys\target\debug\build\libR-sys-842f33bdfa0c1edf\build-script-build` (exit code: 101)
  --- stdout
  cargo:rustc-env=R_HOME=C:\Program Files\R\R-4.0.2
  cargo:r_home=C:\Program Files\R\R-4.0.2
  cargo:rustc-link-search=C:\Program Files\R\R-4.0.2\bin\x64
  cargo:rustc-link-lib=dylib=R
  cargo:rerun-if-changed=build.rs
  cargo:rerun-if-changed=wrapper.h
  cargo:rerun-if-changed=C:\Program Files\R\R-4.0.2\include\Rinternals.h
  cargo:rerun-if-changed=C:\msys64\mingw64\x86_64-w64-mingw32\include\stdio.h
  cargo:rerun-if-changed=C:\msys64\mingw64\x86_64-w64-mingw32\include\corecrt_stdio_config.h
  cargo:rerun-if-changed=C:\msys64\mingw64\x86_64-w64-mingw32\include\corecrt.h
  cargo:rerun-if-changed=C:\msys64\mingw64\x86_64-w64-mingw32\include\_mingw.h
  cargo:rerun-if-changed=C:\msys64\mingw64\x86_64-w64-mingw32\include/_mingw_mac.h
  cargo:rerun-if-changed=C:\msys64\mingw64\x86_64-w64-mingw32\include/_mingw_secapi.h
  cargo:rerun-if-changed=C:\msys64\mingw64\lib\clang\11.0.0\include\vadefs.h
  cargo:rerun-if-changed=C:\msys64\mingw64\x86_64-w64-mingw32\include\vadefs.h
  cargo:rerun-if-changed=C:\msys64\mingw64\x86_64-w64-mingw32\include\_mingw.h
  cargo:rerun-if-changed=C:\msys64\mingw64\x86_64-w64-mingw32\include/sdks/_mingw_ddk.h
  cargo:rerun-if-changed=C:\msys64\mingw64\x86_64-w64-mingw32\include\_mingw_off_t.h
  cargo:rerun-if-changed=C:\msys64\mingw64\x86_64-w64-mingw32\include\swprintf.inl
  cargo:rerun-if-changed=C:\msys64\mingw64\lib\clang\11.0.0\include\vadefs.h
  cargo:rerun-if-changed=C:\msys64\mingw64\x86_64-w64-mingw32\include\vadefs.h
  cargo:rerun-if-changed=C:\msys64\mingw64\x86_64-w64-mingw32\include\sec_api/stdio_s.h
  cargo:rerun-if-changed=C:\msys64\mingw64\x86_64-w64-mingw32\include\stdio.h
  cargo:rerun-if-changed=C:\msys64\mingw64\lib\clang\11.0.0\include\limits.h
  cargo:rerun-if-changed=C:\msys64\mingw64\x86_64-w64-mingw32\include\limits.h
  cargo:rerun-if-changed=C:\msys64\mingw64\x86_64-w64-mingw32\include\crtdefs.h
  cargo:rerun-if-changed=C:\msys64\mingw64\x86_64-w64-mingw32\include\corecrt.h
  cargo:rerun-if-changed=C:\msys64\mingw64\lib\clang\11.0.0\include\stddef.h
  cargo:rerun-if-changed=C:\msys64\mingw64\lib\clang\11.0.0\include/__stddef_max_align_t.h
  cargo:rerun-if-changed=C:\Program Files\R\R-4.0.2\include\R_ext/Arith.h
  cargo:rerun-if-changed=C:\Program Files\R\R-4.0.2\include\R_ext/libextern.h
  cargo:rerun-if-changed=C:\msys64\mingw64\x86_64-w64-mingw32\include\math.h
  cargo:rerun-if-changed=C:\msys64\mingw64\x86_64-w64-mingw32\include\crtdefs.h
  cargo:rerun-if-changed=C:\Program Files\R\R-4.0.2\include\R_ext/Boolean.h
  cargo:rerun-if-changed=C:\Program Files\R\R-4.0.2\include\R_ext/Complex.h
  cargo:rerun-if-changed=C:\Program Files\R\R-4.0.2\include\R_ext/Error.h
  cargo:rerun-if-changed=C:\Program Files\R\R-4.0.2\include\R_ext/Memory.h
  cargo:rerun-if-changed=C:\msys64\mingw64\lib\clang\11.0.0\include\stddef.h
  cargo:rerun-if-changed=C:\Program Files\R\R-4.0.2\include\R_ext/Utils.h
  cargo:rerun-if-changed=C:\Program Files\R\R-4.0.2\include\R_ext/Boolean.h
  cargo:rerun-if-changed=C:\Program Files\R\R-4.0.2\include\R_ext/Complex.h
  cargo:rerun-if-changed=C:\msys64\mingw64\lib\clang\11.0.0\include\stddef.h
  cargo:rerun-if-changed=C:\Program Files\R\R-4.0.2\include\R_ext/Print.h
  cargo:rerun-if-changed=C:\msys64\mingw64\lib\clang\11.0.0\include\stdarg.h
  cargo:rerun-if-changed=C:\Program Files\R\R-4.0.2\include\R_ext/Rdynload.h
  cargo:rerun-if-changed=C:\Program Files\R\R-4.0.2\include\R_ext/Boolean.h
  cargo:rerun-if-changed=C:\Program Files\R\R-4.0.2\include\R_ext/libextern.h
  cargo:rerun-if-changed=C:\Program Files\R\R-4.0.2\include\Rconfig.h
  cargo:rerun-if-changed=C:\Program Files\R\R-4.0.2\include\Rembedded.h
  cargo:rerun-if-changed=C:\Program Files\R\R-4.0.2\include\R_ext/Boolean.h
  cargo:rerun-if-changed=C:\Program Files\R\R-4.0.2\include\Rversion.h
  cargo:rerun-if-changed=C:\Program Files\R\R-4.0.2\include\R_ext/Parse.h
  cargo:rerun-if-changed=C:\Program Files\R\R-4.0.2\include\R_ext/Error.h
  cargo:r_version=262146

  --- stderr
  thread 'main' panicked at 'Could not obtain R version: Custom { kind: Other, error: "Cannot find R major version" }', build.rs:277:59
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src/panicking.rs:483
     1: core::panicking::panic_fmt
               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\core\src/panicking.rs:85
     2: core::option::expect_none_failed
               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\core\src/option.rs:1234
     3: core::result::Result<T,E>::expect
               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\library\core\src/result.rs:933
     4: build_script_build::generate_bindings
               at .\C:\Users\hiroaki-yutani\Documents\repo\R\libR-sys/build.rs:277
     5: build_script_build::main
               at .\C:\Users\hiroaki-yutani\Documents\repo\R\libR-sys/build.rs:352
     6: core::ops::function::FnOnce::call_once
               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\library\core\src\ops/function.rs:227
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
</details>

**Comment by clauswilke** [comment]
Ah, yes, I encountered this before. Windows doesn't like double quotes in command strings. Should be fixed now.

**Comment by yutannihilation** [comment]
Hmm, I really don't understand why, but you still need to use raw string (`r"..."`) here 

https://github.com/clauswilke/libR-sys/blob/c3d02747002a19ac8db1996d715ba3c049719495/build.rs#L179

otherwise I get:

```
"Error: unexpected end of input\r\nExecution halted\r\n"
```

**Comment by yutannihilation** [comment]
Anyway, except for it, I confirmed `cargo test` works fine on MSYS2 MinGW32!

**Comment by clauswilke** [comment]
Super! I'll try to write a GH action that generates the bindings for 64 bit and then builds the 32 bit tests with that. Should be possible.

**Comment by clauswilke** [comment]
@yutannihilation Strangely `cargo test` doesn't work for me. It compiles and then the test crashes:
https://github.com/extendr/libR-sys/pull/27/checks?check_run_id=1552633480#step:7:218

**Comment by clauswilke** [comment]
@yutannihilation I'm still confused that `cargo test` works for you but not for me. Could you try two quick things:

- I committed my generated Windows bindings to the repo. Could you try them by simply running `cargo test --no-default-features -- --test-threads=1` in a 32-bit environment?

- Are my bindings any different from the ones you got? Mine are here: https://github.com/clauswilke/libR-sys/blob/precomputed_bindings/bindings/bindings-windows-x86_64-R4.0.rs

**Comment by yutannihilation** [comment]
Ahh, I found the difference. I didn't specify `--target=i686-pc-windows-gnu`, sorry.

**Comment by yutannihilation** [comment]
Here's the error I got:

```
running 19 tests
test bindgen_test_layout_R_inpstream_st ... FAILED
test bindgen_test_layout_R_outpstream_st ... FAILED
test bindgen_test_layout_R_CMethodDef ... FAILED
test bindgen_test_layout_R_CallMethodDef ... FAILED
test bindgen_test_layout_Rcomplex ... ok
test bindgen_test_layout___mingw_dbl_type_t__bindgen_ty_1 ... ok
test bindgen_test_layout___mingw_dbl_type_t ... ok
test bindgen_test_layout___mingw_flt_type_t ... ok
test bindgen_test_layout___mingw_ldbl_type_t__bindgen_ty_1 ... ok
test bindgen_test_layout___mingw_ldbl_type_t ... ok
test bindgen_test_layout__complex ... ok
test bindgen_test_layout__exception ... FAILED
test bindgen_test_layout__iobuf ... FAILED
test bindgen_test_layout_max_align_t ... ok
test bindgen_test_layout_localeinfo_struct ... FAILED
test bindgen_test_layout_tagLC_ID ... ok
test bindgen_test_layout_threadlocaleinfostruct ... FAILED
test bindgen_test_layout_threadlocaleinfostruct__bindgen_ty_1 ... FAILED
test tests::test_eval ... ok

failures:

---- bindgen_test_layout_R_inpstream_st stdout ----
thread 'bindgen_test_layout_R_inpstream_st' panicked at 'assertion failed: `(left == right)`
  left: `96`,
 right: `128`: Size of: R_inpstream_st', C:\Users\hiroaki-yutani\Documents\repo\R\libR-sys\target\i686-pc-windows-gnu\debug\build\libR-sys-2ff05451443e7a22\out/bindings.rs:5929:5

---- bindgen_test_layout_R_outpstream_st stdout ----
thread 'bindgen_test_layout_R_outpstream_st' panicked at 'assertion failed: `(left == right)`
  left: `28`,
 right: `48`: Size of: R_outpstream_st', C:\Users\hiroaki-yutani\Documents\repo\R\libR-sys\target\i686-pc-windows-gnu\debug\build\libR-sys-2ff05451443e7a22\out/bindings.rs:5820:5

---- bindgen_test_layout_R_CMethodDef stdout ----
thread 'bindgen_test_layout_R_CMethodDef' panicked at 'assertion failed: `(left == right)`
  left: `16`,
 right: `32`: Size of: R_CMethodDef', C:\Users\hiroaki-yutani\Documents\repo\R\libR-sys\target\i686-pc-windows-gnu\debug\build\libR-sys-2ff05451443e7a22\out/bindings.rs:4081:5

---- bindgen_test_layout_R_CallMethodDef stdout ----
thread 'bindgen_test_layout_R_CallMethodDef' panicked at 'assertion failed: `(left == right)`
  left: `12`,
 right: `24`: Size of: R_CallMethodDef', C:\Users\hiroaki-yutani\Documents\repo\R\libR-sys\target\i686-pc-windows-gnu\debug\build\libR-sys-2ff05451443e7a22\out/bindings.rs:4142:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- bindgen_test_layout__exception stdout ----
thread 'bindgen_test_layout__exception' panicked at 'assertion failed: `(left == right)`
  left: `32`,
 right: `40`: Size of: _exception', C:\Users\hiroaki-yutani\Documents\repo\R\libR-sys\target\i686-pc-windows-gnu\debug\build\libR-sys-2ff05451443e7a22\out/bindings.rs:2986:5

---- bindgen_test_layout__iobuf stdout ----
thread 'bindgen_test_layout__iobuf' panicked at 'assertion failed: `(left == right)`
  left: `32`,
 right: `48`: Size of: _iobuf', C:\Users\hiroaki-yutani\Documents\repo\R\libR-sys\target\i686-pc-windows-gnu\debug\build\libR-sys-2ff05451443e7a22\out/bindings.rs:763:5

---- bindgen_test_layout_localeinfo_struct stdout ----
thread 'bindgen_test_layout_localeinfo_struct' panicked at 'assertion failed: `(left == right)`
  left: `8`,
 right: `16`: Size of: localeinfo_struct', C:\Users\hiroaki-yutani\Documents\repo\R\libR-sys\target\i686-pc-windows-gnu\debug\build\libR-sys-2ff05451443e7a22\out/bindings.rs:346:5

---- bindgen_test_layout_threadlocaleinfostruct stdout ----
thread 'bindgen_test_layout_threadlocaleinfostruct' panicked at 'assertion failed: `(left == right)`
  left: `216`,
 right: `352`: Size of: threadlocaleinfostruct', C:\Users\hiroaki-yutani\Documents\repo\R\libR-sys\target\i686-pc-windows-gnu\debug\build\libR-sys-2ff05451443e7a22\out/bindings.rs:534:5

---- bindgen_test_layout_threadlocaleinfostruct__bindgen_ty_1 stdout ----
thread 'bindgen_test_layout_threadlocaleinfostruct__bindgen_ty_1' panicked at 'assertion failed: `(left == right)`
  left: `16`,
 right: `32`: Size of: threadlocaleinfostruct__bindgen_ty_1', C:\Users\hiroaki-yutani\Documents\repo\R\libR-sys\target\i686-pc-windows-gnu\debug\build\libR-sys-2ff05451443e7a22\out/bindings.rs:463:5


failures:
    bindgen_test_layout_R_CMethodDef
    bindgen_test_layout_R_CallMethodDef
    bindgen_test_layout_R_inpstream_st
    bindgen_test_layout_R_outpstream_st
    bindgen_test_layout__exception
    bindgen_test_layout__iobuf
    bindgen_test_layout_localeinfo_struct
    bindgen_test_layout_threadlocaleinfostruct
    bindgen_test_layout_threadlocaleinfostruct__bindgen_ty_1

test result: FAILED. 10 passed; 9 failed; 0 ignored; 0 measured; 0 filtered out

[1] 1
error: test failed, to rerun pass '--lib'
```

**Comment by clauswilke** [comment]
Ah, these are the sanity checks bindgen inserts to verify that nothing in the system has changed since the bindings were generated, see e.g. here: 
https://github.com/clauswilke/libR-sys/blob/b90098ed2ee92e5b60812b6b705889a119691ff2/bindings/bindings-windows-x86_64-R4.0.rs#L5928-L5933

It's possible that none of them actually matter for using the generated bindings. Or, if there are one or two constants that are wrong, we could manually fix them.

**Comment by yutannihilation** [comment]
Oh, I see. As `test tests::test_eval` passes, I hope this doesn't matter in actual. Do you think this is the same error as the one GitHub Actions CI crashes with?

**Comment by clauswilke** [comment]
Yes, I think so. I've read through the bindings file and I don't really see any place where it sets constants that would be different under 32 bit, except in these assertion statements. If this is true then we could create 32-bit bindings by just removing or disabling the problematic assertions.

I'm also still trying the cross-compilation.

**Comment by clauswilke** [comment]
@yutannihilation Could you try this bindings file:
https://github.com/clauswilke/libR-sys/blob/precomputed_bindings/bindings/bindings-windows-x86-R4.0.rs
(If you just check out the latest version of the branch it should use it directly.)

I got it from cross-compiling on 64-bit to 32-bit. It has a ton of changes relative to `x86_64`, and the tests still crash. Maybe cross-compiling made it worse?

**Comment by yutannihilation** [comment]
Thanks, but it still fails.

```
running 19 tests
test bindgen_test_layout_R_CallMethodDef ... ok
test bindgen_test_layout_R_CMethodDef ... ok
test bindgen_test_layout_R_inpstream_st ... ok
test bindgen_test_layout_R_outpstream_st ... ok
test bindgen_test_layout_Rcomplex ... ok
test bindgen_test_layout___mingw_dbl_type_t ... ok
test bindgen_test_layout___mingw_dbl_type_t__bindgen_ty_1 ... ok
test bindgen_test_layout___mingw_flt_type_t ... ok
test bindgen_test_layout___mingw_ldbl_type_t__bindgen_ty_1 ... ok
test bindgen_test_layout__complex ... ok
test bindgen_test_layout__exception ... ok
test bindgen_test_layout__iobuf ... ok
test bindgen_test_layout_localeinfo_struct ... ok
test bindgen_test_layout_tagLC_ID ... ok
test bindgen_test_layout_threadlocaleinfostruct ... ok
test bindgen_test_layout_threadlocaleinfostruct__bindgen_ty_1 ... ok
test bindgen_test_layout_max_align_t ... FAILED
test bindgen_test_layout___mingw_ldbl_type_t ... FAILED
test tests::test_eval ... ok

failures:

---- bindgen_test_layout_max_align_t stdout ----
thread 'bindgen_test_layout_max_align_t' panicked at 'assertion failed: `(left == right)`
  left: `16`,
 right: `24`: Size of: max_align_t', C:\Users\hiroaki-yutani\Documents\repo\R\libR-sys\target\i686-pc-windows-gnu\debug\build\libR-sys-2ff05451443e7a22\out/bindings.rs:2688:5

---- bindgen_test_layout___mingw_ldbl_type_t stdout ----
thread 'bindgen_test_layout___mingw_ldbl_type_t' panicked at 'assertion failed: `(left == right)`
  left: `8`,
 right: `4`: Alignment of __mingw_ldbl_type_t', C:\Users\hiroaki-yutani\Documents\repo\R\libR-sys\target\i686-pc-windows-gnu\debug\build\libR-sys-2ff05451443e7a22\out/bindings.rs:2974:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    bindgen_test_layout___mingw_ldbl_type_t
    bindgen_test_layout_max_align_t

test result: FAILED. 17 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out

[1] 1
error: test failed, to rerun pass '--lib'
```

**Comment by clauswilke** [comment]
It's progress, though. Now only two tests fail, and they are not related to the R interface.
